# Generated by Django 3.2.13 on 2022-06-25 10:50

from django.db import migrations, models
import gsheets.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('order_name', models.CharField(max_length=200, verbose_name='Name')),
                ('price_usd', models.IntegerField()),
                ('price_rub', models.IntegerField(blank=True)),
                ('delivery_period', models.CharField(max_length=200, verbose_name='Date')),
            ],
            bases=(gsheets.mixins.SheetSyncableMixin, models.Model),
        ),
    ]
