# Generated by Django 3.2.13 on 2022-06-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price_rub',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
